version: "3.9"
services:
  reliefexchange_backend:
    container_name: reliefexchange_backend
    restart: unless-stopped
    image: ghcr.io/aritrosaha10/relief-exchange-backend:latest 
    ports:
      - 7000:5050
    environment:
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
